# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos-root";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos-root".device = "/dev/disk/by-uuid/0d12f070-7fe1-45ac-bbb9-e1efdca6e54f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/29E7-0445";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/kingston" =
    { device = "/dev/mapper/kingston";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."kingston".device = "/dev/disk/by-uuid/29d005dc-d213-455b-895e-34083696e8be";

  fileSystems."/jellyfin" =
    { device = "/mnt/kingston/jellyfin";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/inc" =
    { device = "/mnt/kingston/st";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
