# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "uas"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."nixos-root".device =
    "/dev/disk/by-uuid/3e6d255d-3e55-4448-ad41-95e293cfff3d";

  fileSystems."/" = {
    device = "/dev/mapper/nixos-root";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/29E7-0445";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  boot.initrd.luks.devices."kingston".device = "/dev/disk/by-uuid/00ddcc85-31c4-4b18-b478-d4b06790c333";

  fileSystems."/home" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/st" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=st" ];
    };

  fileSystems."/var/lib/nextcloud" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=var/lib/nextcloud" ];
    };

  fileSystems."/var/lib/sbctl" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=var/lib/sbctl" ];
    };

  fileSystems."/var/lib/redis-nextcloud" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=var/lib/redis-nextcloud" ];
    };

  fileSystems."/var/lib/gitolite" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=var/lib/gitolite" ];
    };

  fileSystems."/var/lib/taskchampion-sync-server" =
    { device = "/dev/mapper/kingston";
      fsType = "btrfs";
      options = [ "subvol=var/lib/taskchampion-sync-server" ];
    };

  boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/d93797fe-adbb-47a2-beeb-5ddc34e1673a";

  boot.resumeDevice = "/dev/mapper/swap";

  swapDevices = [
    { device = "/dev/mapper/swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
