{
  pkgs,
  inputs,
  username,
  ...
}:
{
  home.packages = with pkgs; [
    waypaper
    inputs.adw-bluetooth.packages.${pkgs.stdenv.hostPlatform.system}.default
    inputs.hypr-contrib.packages.${pkgs.stdenv.hostPlatform.system}.grimblast
    inputs.hyprpicker.packages.${pkgs.stdenv.hostPlatform.system}.hyprpicker
    swww
    nwg-displays
    hyprpolkitagent
    gradia
    copyq
    grim
    slurp
    wlogout
    wl-clip-persist
    cliphist
    wf-recorder
    glib
    wayland
    direnv
  ];
}
